apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-zxvf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pgji-tenant/rhtap-demo-app/hacbs-test-project-zxvf@sha256:165841ffec96dd8eaf4abd87f2d9697372d151e26118b50f62316090b7172856
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
