apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zxvf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zxvf
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zxvf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zxvf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zxvf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pgji-tenant/rhtap-demo-app/hacbs-test-project-zxvf@sha256:165841ffec96dd8eaf4abd87f2d9697372d151e26118b50f62316090b7172856
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
